#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/../.."

DEPLOY_ENV="${DEPLOY_ENV:-local}"
NETWORK_URL="localhost:8080"
while (($# > 0)); do
  arg="$1"
  shift 1
  case "$arg" in
  --help)
    cat <<-EOF

	Deploys nns-dapp and required canisters to localhost.

	Usage: "$0 [--nobuild] [--help]"

	Flags:
	  --help == print this help
	  --nobuild == set DEPLOY_ENV=nobuild so that the existing wasm is used.

	EOF
    exit 0
    ;;
  --nobuild) DEPLOY_ENV=nobuild ;;
  esac
done

wait_for_url() {
  local url="$1"
  local seconds="${2:-10}"
  local options="${3:-}"
  : "Waiting up to ${seconds} seconds for: ${url}"
  for ((i = 0; i < seconds; i++)); do
    if curl ${options:+${options}} -so /dev/null "$url"; then
      return 0
    else
      sleep 1
    fi
  done
  echo "URL not ready after ${seconds}s: curl ${options:+${options}} -so /dev/null $url" >&2
  return 1
}

: "Waiting for the network to be present at: ${NETWORK_URL}"
: "Note: The network is expected to complain, with a non-200 response, that we haven't specified the canister ID."
wait_for_url "$NETWORK_URL"

cat <<EOF
: "Creating and deploying canisters..."
: "... the order of these canisters matters"
dfx canister create --all || echo Canisters may have been created already. Proceeding...
: "... we actually need specific canister IDs for governance + ledger, sadly.  Seting all canister IDs:"
cat <<< $(jq '.governance.local = "rrkah-fqaaa-aaaaa-aaaaq-cai" | .ledger.local="ryjl3-tyaaa-aaaaa-aaaba-cai" | .internet_identity.local = "r7inp-6aaaa-aaaaa-aaabq-cai" | .["nns-dapp"].local = "rkp4c-7iaaa-aaaaa-aaaca-cai"' .dfx/local/canister_ids.json) > .dfx/local/canister_ids.json

echo yes | dfx deploy --mode reinstall --argument '(record {
  send_whitelist = vec {};
  minting_account = "a825baa57b585c51459608693d348546c4a61bab1ef6521543fb1e8daeff4b4a";
  transaction_window = null;
  initial_values = vec { record { "5b315d2f6702cb3a27d826161797d7b2c2e131cd312aece51d4d5574d1247087"; record { e8s=100_000_000_000 } }; };
  archive_options = null;
  max_message_size_bytes = null;
})' ledger

dfx deploy internet_identity
EOF

II_CANISTER_ID="$(dfx canister --network local id internet_identity)"
IDENTITY_SERVICE_URL="http://${II_CANISTER_ID}.localhost:8080"
OWN_CANISTER_ID="$(dfx canister --network local id nns-dapp)"

FETCH_ROOT_KEY=true OWN_CANISTER_ID="$OWN_CANISTER_ID" REDIRECT_TO_LEGACY=svelte DEPLOY_ENV="$DEPLOY_ENV" IDENTITY_SERVICE_URL="$IDENTITY_SERVICE_URL" dfx deploy --network local --argument '(null)' nns-dapp

: "Waiting for the canister to return with HTTP code 200..."
NNS_DAPP_CANISTER_ID="$(dfx canister --network local id nns-dapp)"
NNS_DAPP_CANISTER_URL="${NNS_DAPP_CANISTER_ID}.${NETWORK_URL}"
wait_for_url "$NNS_DAPP_CANISTER_URL" 10 --fail

echo OK
