#!/usr/bin/env bash
set -euo pipefail

[[ "$1" != "--help" ]] || {
  cat <<-EOF

	Runs e2e tests against one of the nns-XXX.winning.gold endpoints

	Example usages:
	  # Run all tests against nns-prod:
	  ./test-winning
	  # Run just the redirect tests against nns-svelte:
	  REDIRECT_TO_LEGACY=svelte ./test-winning --spec /specs/redirect-to-legacy.e2e.ts
	EOF
  exit 0
}

REDIRECT_TO_LEGACY="${REDIRECT_TO_LEGACY:-prod}"
export REDIRECT_TO_LEGACY
NNS_DAPP_URL="$(curl -v "https://nns-${REDIRECT_TO_LEGACY}.winning.gold" 2>&1 | awk '/location:/{print $3}' | tr -d '[:space:]')"
export NNS_DAPP_URL

npm run wdio -- "${@}"
