#!/usr/bin/env bash
set -euo pipefail

cd "$(realpath "$(dirname "$0")")/.."

NNS_DAPP_URL="$(jq -r .OWN_CANISTER_URL ../frontend/ts/src/config.json)"
REDIRECT_TO_LEGACY="$(jq -r .REDIRECT_TO_LEGACY ../frontend/ts/src/config.json)"

export NNS_DAPP_URL
export REDIRECT_TO_LEGACY

rm -fr screenshots
npm run wdio -- "${@}"
