#!/usr/bin/env bash

# NOT TO BE MERGED INTO MAIN
# Used to compare this config with that created by "update_config.sh".

set -euo pipefail
variant="${1:-mainnet}"
DEPLOY_ENV="$variant" ./update_config.sh
DFX_NETWORK="$variant" bash config.sh

diff -y -W200 <(jq --sort-keys . frontend/ts/src/config.json | sed 's/,$//g') <(jq --sort-keys . config.json | sed 's/,$//g') || true
jsondiff frontend/ts/src/config.json config.json | jq .
