#!/usr/bin/env bash
set -euo pipefail
SOURCE_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")/.."
PATH="$SOURCE_DIR:$PATH"

print_help() {
  cat <<-EOF

	Finds CI builds of the current commit.

	Note: This searches through gihub logs.  Only fairly recent logs are readily accessible.
	      Older runs may be found using high velues for the '--limit' flag but this is very slow.

	EOF
}

# Source the clap.bash file ---------------------------------------------------
source "$SOURCE_DIR/clap.bash"
# Define options
clap.define short=l long=limit desc="The number of runs to search though" variable=DFX_LIMIT default="200"
clap.define short=c long=commit desc="The commit, tag or reference to find" variable=DFX_COMMIT default="HEAD"
# Source the output file ----------------------------------------------------------
source "$(clap.build)"

ci_build_run_id="$("$SOURCE_DIR/nns-dapp/get-ci-build-run" --commit "$DFX_COMMIT" --limit "$DFX_LIMIT")"

echo "https://github.com/dfinity/nns-dapp/actions/runs/$ci_build_run_id"
