#!/usr/bin/env bash
set -euo pipefail
SOURCE_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")/.."

# Source the clap.bash file ---------------------------------------------------
source "$SOURCE_DIR/clap.bash"
# Define options
clap.define short=n long=network desc="The dfx network to use" variable=DFX_NETWORK default="local"
clap.define short=i long=identity desc="The dfx identity to use" variable=DFX_IDENTITY default="${DFX_IDENTITY:-$(dfx identity whoami)}"
clap.define long=mode desc="The dfx install mode" variable=DFX_MODE default="upgrade"
clap.define short=a long=assets desc="The assets.tar.xz to split" variable=ORIGINAL_ASSETS_TAR_XZ default="out/assets.tar.xz"
clap.define long=argument_file desc="The .did file with the canister argument" variable=ARGUMENT_FILE default="out/nns-dapp-arg-local.did"
clap.define short=w long=wasm desc="The canister WASM to install" variable=WASM default="out/nns-dapp_noassets.wasm.gz"
# Source the output file ----------------------------------------------------------
source "$(clap.build)"

set -x

mkdir -p out
CANISTER_NAME="nns-dapp"

"$SOURCE_DIR/nns-dapp/split-assets" --assets "$ORIGINAL_ASSETS_TAR_XZ"

ls -l out/chunks

ARGUMENT="$(cat "$ARGUMENT_FILE")"

# There have been issues with the uploading of assets causing
# "heap out of bounds" so we output logs to help debug when it happens
# again.
# The canister only keeps a small amount of logs so we output them
# before and after every step to miss as little as possible.
dfx canister logs --network "$DFX_NETWORK" "$CANISTER_NAME"

#dfx canister install --mode "$DFX_MODE" --yes --network "$DFX_NETWORK" "$CANISTER_NAME" --argument "$ARGUMENT" --wasm "$WASM"
dfx canister install --mode "$DFX_MODE" --yes --network "$DFX_NETWORK" "$CANISTER_NAME" --argument "$ARGUMENT" --wasm "out/nns-dapp.wasm.gz"

dfx canister logs --network "$DFX_NETWORK" "$CANISTER_NAME"

exit 0

./scripts/nns-dapp/upload-asset-tarball --network "$DFX_NETWORK" --chunk out/chunks/assets.xaa.tar.xz

dfx canister logs --network "$DFX_NETWORK" "$CANISTER_NAME"
./scripts/nns-dapp/upload-asset-tarball --network "$DFX_NETWORK" --chunk out/chunks/assets.xab.tar.xz

dfx canister logs --network "$DFX_NETWORK" "$CANISTER_NAME"
./scripts/nns-dapp/upload-asset-tarball --network "$DFX_NETWORK" --chunk out/chunks/assets.xac.tar.xz

dfx canister logs --network "$DFX_NETWORK" "$CANISTER_NAME"
