#!/usr/bin/env bash
set -euo pipefail
SOURCE_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")/.."
PATH="$SOURCE_DIR:$PATH"

print_help() {
  cat <<-EOF

	Compares the wasm export table to the expected exports.
	EOF
}

# Source the clap.bash file ---------------------------------------------------
source "$SOURCE_DIR/clap.bash"
# Define options
clap.define short=w long=wasm desc="The location of the nns-dapp wasm." variable=DFX_WASM_PATH default="nns-dapp.wasm.gz"
clap.define short=u long=update-golden desc="Update the exports golden file" variable=UPDATE_GOLDEN nargs=0 default="false"
# Source the output file ----------------------------------------------------------
source "$(clap.build)"

GOLDEN_FILE="rs/backend/nns-dapp-exports.txt"

wasm_exports() {
  ic-wasm <(gunzip <"$1") info | sed -nE '/^Exported methods:/,/^]/p' | sed '1d;$d' | sed -E 's/.*"(.*)",/\1/'
}

if [ "$UPDATE_GOLDEN" = "true" ]; then
  echo "Updating golden file"
  wasm_exports "$DFX_WASM_PATH" | sort >"$GOLDEN_FILE"
  exit 0
fi

if diff <(sort "$GOLDEN_FILE") <(wasm_exports "$DFX_WASM_PATH" | sort); then
  echo "Exports match"
else
  echo "Exports do not match"
  echo "If this looks correct, run '$0 --wasm $DFX_WASM_PATH --update-golden' to update the golden file"
  exit 1
fi
