#!/usr/bin/env bash
set -euo pipefail
SOURCE_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")/.."
PATH="$SOURCE_DIR:$PATH"

print_help() {
  cat <<-EOF

	Compares the wasm export table to the expected exports.
	EOF
}

# Source the clap.bash file ---------------------------------------------------
source "$SOURCE_DIR/clap.bash"
# Define options
clap.define short=w long=wasm desc="The location of the nns-dapp wasm." variable=DFX_WASM_PATH default="nns-dapp.wasm"
# Source the output file ----------------------------------------------------------
source "$(clap.build)"

diff <(sort rs/backend/nns-dapp-exports.txt) <(wasm-nm -je <(gunzip <"$DFX_WASM_PATH") | sort)
