#!/usr/bin/env bash
set -euo pipefail
SOURCE_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")/.."
PATH="$SOURCE_DIR:$PATH"

# Source the clap.bash file ---------------------------------------------------
source "$SOURCE_DIR/clap.bash"
# Define options
clap.define short=c long=chunk desc="The asset chunk to upload" variable=CHUNK_TAR_XZ
clap.define short=n long=network desc="The dfx network to use" variable=DFX_NETWORK default="local"
# Source the output file ----------------------------------------------------------
source "$(clap.build)"

encoded_asset_file="$(mktemp)"
echo "( blob \"$(xxd <"$CHUNK_TAR_XZ" -p | sed 's/../\\&/g' | tr -d "\n")\" )" >"$encoded_asset_file"
dfx canister call nns-dapp add_assets_tar_xz --argument-file "$encoded_asset_file" --network "$DFX_NETWORK"
