export const AGGREGATOR_CANISTER_VERSION = "v1";
export const AGGREGATOR_PAGE_SIZE = 10;
export const SALE_PARTICIPATION_RETRY_SECONDS = 2;
export const WATCH_SALE_STATE_EVERY_MILLISECONDS = 10_000;
export const MAX_THEORETICAL_NEURONS_FUND_PARTICIPATION_AMOUNT_ICP = 333_000;
