#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/../../.."

read -rp "HSM Pin: " DFX_HSM_PIN

NEURON_PATH="$HOME/.config/dfx/prod-neuron"
if test -e "$NEURON_PATH"; then
  NEURON="$(cat "$NEURON_PATH")"
else
  read -rp "Neuron ID: " NEURON
fi

AGGREGATOR_CANISTER_ID="3r4gx-wqaaa-aaaaq-aaaia-cai"
WASM="./release/docker/sns_aggregator.wasm"
SHA="$(sha256sum <"$WASM" | awk '{print $1}')"

set ic-admin --pin "$DFX_HSM_PIN" --nns-url https://ic0.app --use-hsm --key-id 01 --slot 0 propose-to-change-nns-canister --proposer "$NEURON" --canister-id "$AGGREGATOR_CANISTER_ID" --mode upgrade --wasm-module-path "$WASM" --summary-file ./release/AGGREGATOR_PROPOSAL.md --wasm-module-sha256 "$SHA"

echo
echo PLEASE REVIEW THIS COMMAND:
echo
echo "${@}"
echo

read -rp "Execute? (y/N)" COMMAND_OK
if [[ "$COMMAND_OK" = [yY] ]]; then
  "${@}"
fi
