#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/../../.."

WASM_FILENAME="sns_aggregator.wasm.gz"
WASM="release/ci/$WASM_FILENAME"
COMMIT="aggregator-release-candidate"
mkdir -p release/ci
./scripts/nns-dapp/download-ci-wasm --commit "$COMMIT" --wasm-filename "$WASM_FILENAME"

if test -f "$WASM"; then
  SHA="$(sha256sum "$WASM" | awk '{print $1}')"
else
  echo "Please populate ${WASM} and run this again."
  exit 1
fi

# The proposal states this hash, so compare it with the hash in the CI build log.
CI_SHA="$(./scripts/nns-dapp/get-hash-from-ci-log --commit "$COMMIT" --filename "$WASM_FILENAME")"
if test -z "${CI_SHA:-}"; then
  {
    echo "ERROR: Found no $WASM_FILENAME hash in the CI build log for $COMMIT."
    echo "       The CI run may be too old, so a rebuild of the commit may be necessary."
    exit 1
  } >&2
fi
if test "$CI_SHA" != "$SHA"; then
  {
    echo "ERROR: The wasm hash differs from the hash in the CI build log."
    echo "       CI build log: $CI_SHA"
    echo "       $WASM: $SHA"
    echo "       Please delete $WASM and run this again."
    exit 1
  } >&2
fi

cat <<EOF >release/AGGREGATOR_PROPOSAL.md
# Upgrade SNS aggregator canister to commit \`$(git rev-parse HEAD)\`
Wasm sha256 hash: \`${SHA}\` (\`${WASM}\`)

## Change Log

* Write about...
* ... what has changed
* ... in simple bullet points

## Commit Log

\`\`\`
+ bash -xc "git log --format='%C(auto) %h %s' $(git rev-parse --short tags/aggregator-prod)..$(git rev-parse --short HEAD) ./rs/sns_aggregator/"
$(bash -xc "git log --format='%C(auto) %h %s' $(git rev-parse --short tags/aggregator-prod)..$(git rev-parse --short HEAD) ./rs/sns_aggregator/")
\`\`\`

## Forum
Please see the forum post here: FORUM_LINK

## Wasm Verification

To build the wasm module yourself and verify its hash, run the following commands from the root of the [nns-dapp repo](https://github.com/dfinity/nns-dapp):

\`\`\`
git fetch  # to ensure you have the latest changes.
git checkout "$(git rev-parse HEAD)"
./scripts/docker-build
sha256sum sns_aggregator.wasm.gz
\`\`\`

## Arg Verification
\`\`\`
ARG='(null : null)'
didc encode "$ARG" | xxd -r -p | sha256sum
\`\`\`
EOF

cat <<EOF >release/AGGREGATOR_ROLLBACK.md
# Downgrade SNS aggregator canister to commit \`$(git rev-parse HEAD)\`
Wasm sha256 hash: \`${SHA}\` (\`${WASM}\`)

## Wasm Verification

To build the wasm module yourself and verify its hash, run the following commands from the root of the nns-dapp repo:

\`\`\`
git fetch  # to ensure you have the latest changes.
git checkout "$(git rev-parse HEAD)"
./scripts/docker-build
sha256sum sns_aggregator.wasm.gz
\`\`\`

## Arg Verification
\`\`\`
ARG='(null : null)'
didc encode "$ARG" | xxd -r -p | sha256sum
\`\`\`
EOF

ARG_DID="./release/sns_aggregator_arg.did"
echo '(null : null)' >"$ARG_DID"
