#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/../../.."

NEURON_PATH="$HOME/.config/dfx/prod-neuron"
if test -e "$NEURON_PATH"; then
  NEURON="$(cat "$NEURON_PATH")"
  echo "Neuron ID: $NEURON (from $NEURON_PATH)"
else
  read -rp "Please enter your Neuron ID: " NEURON
  read -rp "... Store the Neuron ID for future use? (y/N)" STORE_NEURON
  [[ "$STORE_NEURON" != [yY] ]] || {
    mkdir -p "$(dirname "$NEURON_PATH")"
    printf "%s" "$NEURON" >"$NEURON_PATH"
  }
fi

read -rp "HSM Pin: " DFX_HSM_PIN

AGGREGATOR_CANISTER_ID="3r4gx-wqaaa-aaaaq-aaaia-cai"
WASM="./release/docker/sns_aggregator.wasm.gz"
SHA="$(sha256sum <"$WASM" | awk '{print $1}')"

ARG_DID="./release/sns_aggregator_arg.did"
ARG_PATH="./release/sns_aggregator_arg.bin"
didc encode "$(cat "$ARG_DID")" | xxd -r -p >"$ARG_PATH"

PROPOSAL_TEXT="./release/AGGREGATOR_PROPOSAL.md"

# Verifies that the forum link placeholder has been replaced.
FORUM_PLACEHOLDER="FORUM_LINK"
# ... Verifies that the template contains the placeholder:
grep -w "$FORUM_PLACEHOLDER" scripts/sns/aggregator/release-template >/dev/null || {
  echo "ERROR: The proposal template should have a space for a forum link but"
  echo "       could not find $FORUM_PLACEHOLDER in: scripts/sns/aggregator/release-template"
  exit 1
} >&2
# ... Verifies that the proposal text does not contain the placeholder:
if grep -w "$FORUM_PLACEHOLDER" "$PROPOSAL_TEXT"; then
  {
    echo "ERROR: Please make a forum post and put the link in the proposal text,"
    echo "       replacing the placeholder '$FORUM_PLACEHOLDER'."
    echo "       If you have a strong reason for not making a forum post, please"
    echo "       delete the section for the forum post."
    echo
    echo "SUGGESTED FORUM TEMPLATE:"
    cat scripts/sns/aggregator/release-forum-template.md
    exit 1
  } >&2
fi

set ic-admin --pin "$DFX_HSM_PIN" --nns-url https://ic0.app --use-hsm --key-id 01 --slot 0 propose-to-change-nns-canister --proposer "$NEURON" --canister-id "$AGGREGATOR_CANISTER_ID" --mode upgrade --wasm-module-path "$WASM" --summary-file "$PROPOSAL_TEXT" --wasm-module-sha256 "$SHA" --arg "$ARG_PATH"

echo
echo PLEASE REVIEW THIS COMMAND:
echo
echo "${@}"
echo

read -rp "Execute? (y/N)" COMMAND_OK
if [[ "$COMMAND_OK" = [yY] ]]; then
  "${@}"
fi
