//! Verifies that the Candid interface served by the canister matches the
//! committed `sns_aggregator.did` exactly, so that drift between the two is
//! caught in CI.
//!
//! This module is only compiled with the `reconfigurable` feature (see the
//! `mod` declaration in `lib.rs`): the committed `.did` documents the full
//! interface, including the feature-gated `reconfigure` method. CI runs the
//! Rust tests with `--all-features`.
#![allow(clippy::panic)]
#![allow(clippy::expect_used)]
#![allow(clippy::unwrap_used)]

use candid_parser::utils::{service_equal, CandidSource};

#[test]
fn test_implemented_interface_matches_declared_interface_exactly() {
    let declared_interface_path = "sns_aggregator.did";
    let declared_interface = std::fs::read(declared_interface_path).unwrap();
    let declared_interface = String::from_utf8(declared_interface).unwrap();
    let declared_interface = CandidSource::Text(&declared_interface);

    // `__export_service()` is generated by the crate-level `export_service!()`
    // macro in `lib.rs` from the methods registered via `candid_method` (both
    // the explicit annotations and the ones ic-cdk auto-generates for each
    // exported endpoint). It is the interface the canister actually serves.
    let implemented_interface_str = super::__export_service();
    let implemented_interface = CandidSource::Text(&implemented_interface_str);

    let result = service_equal(implemented_interface, declared_interface);
    assert!(result.is_ok(), "Error: {result:?}");
}
