#!/bin/bash

pushd "$(dirname "$(realpath "$0")")/../frontend/ts" || exit >/dev/null # Move to the script's directory.

if [ ! -d "node_modules" ]; then
  npm install
fi

# This isn't needed by the CLI, but is done to keep the TS compiler happy.
DEPLOY_ENV=mainnet ../../config.sh >/dev/null

npm run ic-hardware-wallet-cli --silent -- "${@}"
popd || exit >/dev/null
