name: 'Needed jobs succeeded'
description: Checks that the jobs needed by the current job succeeded.
#inputs:
#  needs:
#    description: "JSON describing the needed jobs; this can be obtained with '${{ toJson(needs) }}'."
#    required: true
runs:
  using: "composite"
  steps:
    - name: "Check that all jobs in 'needs' are successful."
      run: |
          all_jobs="$(echo '${{ toJson(needs) }}' | jq 'to_entries[]')"
          [[ "$all_jobs" != "" ]] || {
             echo "ERROR: No needs found"
          }
          unsuccessful_jobs="$(echo '${{ toJson(needs) }}' | jq 'to_entries[] | select(.value.result != "success")')"
          if  [[ "$unsuccessful_jobs" == "" ]]
          then echo "Congratulations, young Frodo."
          else echo "You shall not pass:  Some required tests did not succeed:"
               echo "$unsuccessful_jobs"
               exit 1
          fi
