name: 'Needed jobs succeeded'
description: Checks that the jobs needed by the current job succeeded.
inputs:
  needs:
    description: "JSON describing the needed jobs."
    required: true
runs:
  using: "composite"
  steps:
    - name: "Check that we have inputs"
      shell: bash
      run: |
          all_jobs="$(echo '${{ inputs.needs }}' | jq 'to_entries[]')"
          [[ "$all_jobs" != "" ]] || {
             echo "ERROR: No needs found"
             exit 1
          }
    - name: "Check that all jobs in 'needs' are successful"
      shell: bash
      run: |
          unsuccessful_jobs="$(echo '${{ inputs.needs }}' | jq 'to_entries[] | select(.value.result != "success")')"
          if  [[ "$unsuccessful_jobs" == "" ]]
          then echo "Congratulations, you may pass."
          else echo "You shall not pass:  Some required tests did not succeed:"
               echo "$unsuccessful_jobs"
               exit 1
          fi
