name: 'Run Playwright e2e test shard'
description: |
  Set up a test environment and run (a subset of) the Playwright end-to-end tests.
inputs:
  shard_count:
    description: "The total number shards to split the tests into"
    required: false
    default: 1
  shard_number:
    description: "Which of the shards to run"
    required: false
    default: 1
runs:
  using: "composite"
  steps:
    - name: Set up Playwright e2e test
      uses: ./.github/actions/test-e2e
    - name: Run Playwright end-to-end tests
      shell: bash
      working-directory: frontend
      run: PLAYWRIGHT_BASE_URL="$(../scripts/dfx-canister-url nns-dapp)" npm run test-e2e -- $(ls src/tests/e2e/*.spec.ts | cat | split -n r/${{ inputs.shard_number }}/${{ inputs.shard_count }})
    - name: Upload Playwright results
      uses: actions/upload-artifact@v3
      if: ${{ failure() }}
      with:
        name: playwright-failure-results
        path: |
          frontend/playwright-report/*
          frontend/playwright-results/*
        retention-days: 3
    - name: Stop replica
      shell: bash
      run: dfx stop
