#!/usr/bin/env bash
set -euxo pipefail

export DFX_NETWORK=small14
TESTNET=small14
IC_COMMIT=997ab2e9cc49189302fe54c1e60709abfbeb1d42
IC_DOWNLOAD=$IC_COMMIT
IC_DIR="$HOME/dfn/ic-github/"
ND_COMMIT=f32509a6a44694c45f65c2587e85456be8b32e17
ND_DIR="$HOME/dfn/nns-dapp/branches/testnet-environments"


cd "$ND_DIR"
dfx identity use ident-1


( set -euxo pipefail
  cd "$ND_DIR"
  git fetch
  git checkout "$ND_COMMIT"
git reset --hard "$ND_COMMIT"
rm -fr target/
IC_COMMIT=$IC_DOWNLOAD jq '.defaults.build.config.IC_COMMIT="\(env.IC_COMMIT)"' dfx.json >dfx.json.new
mv dfx.json.new dfx.json
tail dfx.json
./e2e-tests/scripts/nns-canister-download --ic-commit "$IC_DOWNLOAD"
./e2e-tests/scripts/nns-canister-build --ic-commit "$IC_COMMIT"
say Created canisters
) || say fail fail fail




( set -euxo pipefail
	cd "$IC_DIR"
	cat <<-EOF > test-accounts.json
	{
	  "init_ledger_accounts":["5b315d2f6702cb3a27d826161797d7b2c2e131cd312aece51d4d5574d1247087", "2b8fbde99de881f695f279d2a892b1137bfe81a42d7694e064b1be58701e1138"],
	  "custom_canister_dir": "$ND_DIR/target/ic/"
	}
	EOF

	./testnet/tools/icos_deploy.sh --git-revision "$IC_COMMIT" "$TESTNET" --ansible-args "-e @$PWD/test-accounts.json"
	say Deployed testnet
	( cd testnet/env/$TESTNET/ && ./hosts --nns-nodes | awk '{printf "%s http://[%s]:8080\n", $1, $2}' ; )
	( cd "$ND_DIR" && ./deploy.sh --delete "$DFX_NETWORK" )
	cat <<< $(jq -S '.["nns-governance"][env.DFX_NETWORK]="rrkah-fqaaa-aaaaa-aaaaq-cai"' canister_ids.json) > canister_ids.json
) || say fail fail fail



echo Setting the cycles exchange rate...
  ./scripts/propose --to propose-xdr-icp-conversion-rate --dfx-network "$DFX_NETWORK" --jfdi

  # Allow the cmc canister to create canisters anywhere.
  # Note: The proposal is acepted and executed immediately because there are no neurons apart from the test user.
  # Note: Local dfx has no subnets.
  [[ "$DFX_NETWORK" == "local" ]] || {
    echo Setting the list of subnets CMC is authorized to create canisters in...
    ./scripts/propose --to set-authorized-subnetworks --dfx-network "$DFX_NETWORK" --jfdi
  }


export NNS_URL="$(jq -r '.networks[env.DFX_NETWORK].providers[0]' dfx.json)"

./deploy.sh --sns-wasm "$DFX_NETWORK"

$(dfx cache show)/ic-admin \
  --nns-url "$NNS_URL" \
  propose-to-update-sns-subnet-ids-in-sns-wasm \
  --test-neuron-proposer \
  $(ic-admin --nns-url "$NNS_URL" get-subnet-list | jq -r 'map("--sns-subnet-ids-to-add " + . + " ") | .[]')

( set -euxo pipefail
  ./deploy.sh --ii "$DFX_NETWORK"
  ./deploy.sh --nns-dapp "$DFX_NETWORK"
  say deployed frontends
) || say fail fail fail

# ./mk-sns-config
# ./deploy.sh --sns --ctl-nobuild-nns "$DFX_NETWORK"


# "$HOME"/dfn/nns-dapp/branches/testnet-updates/scripts/testnet-set-canister-ids
#jq 'to_entries | map({key:.key, value: { (env.DFX_NETWORK): .value[env.DFX_NETWORK] }}) | del(..|nulls) | from_entries' canister_ids.json



