#!/usr/bin/env bash
set -euxo pipefail

# sdk has broken; this branch should fix it.
#export PATH="/home/max/dfn/sdk/branches/spofford/global-args/target/debug:$PATH"

export DFX_NETWORK=small13
TESTNET=small13
IC_COMMIT=51b8f11db27c70c252eedc5b4b75aa6417636772 # master Wed Aug 31 10:46:12 2022 +0000
IC_DOWNLOAD=$IC_COMMIT
IC_DIR="$HOME"/dfn/ic-github/
ND_COMMIT=27d5755531c2bd2633289a49a0ec65098582f1dc # main Sep 06
ND_DIR="$HOME"/dfn/nns-dapp/branches/testnet-environments
OC_COMMIT=896b202b597d07fc6e3b6fb4b8f477f690d37320
OC_DIR="$HOME"/dfn/open-chat

# Older values, known to work:
#IC_COMMIT=08716da25d35ffcf7cc190ca952ad52e269c57a2 # master Thu Aug 25 12:40:41 2022 +0000
#ND_COMMIT=ef5d3fb805bfc8b3828b0eb70fdd44719800fc81 # main Thu Aug 25 14:02:34 2022 +0200



cd "$ND_DIR"
dfx identity use default


( set -euxo pipefail
  cd "$ND_DIR"
  git fetch
  git checkout "$ND_COMMIT"
git reset --hard "$ND_COMMIT"
rm -fr target/
IC_COMMIT=$IC_DOWNLOAD jq '.defaults.build.config.IC_COMMIT="\(env.IC_COMMIT)"' dfx.json >dfx.json.new
mv dfx.json.new dfx.json
tail dfx.json
./e2e-tests/scripts/nns-canister-download --ic-commit "$IC_DOWNLOAD"
./e2e-tests/scripts/nns-canister-build --ic-commit "$IC_COMMIT"
say Created canisters
) || say fail fail fail




( set -euxo pipefail
	cd "$IC_DIR"
	cat <<-EOF > test-accounts.json
	{
	  "init_ledger_accounts":["5b315d2f6702cb3a27d826161797d7b2c2e131cd312aece51d4d5574d1247087"],
	  "custom_canister_dir": "$ND_DIR/target/ic/"
	}
	EOF

	./testnet/tools/icos_deploy.sh --git-revision "$IC_COMMIT" "$TESTNET" --ansible-args "-e @$PWD/test-accounts.json"
	say Deployed testnet
	( cd testnet/env/$TESTNET/ && ./hosts --nns-nodes | awk '{printf "%s http://[%s]:8080\n", $1, $2}' ; )
	( cd "$ND_DIR" && ./deploy.sh --delete "$DFX_NETWORK" )
	cat <<< $(jq -S '.["nns-governance"][env.DFX_NETWORK]="rrkah-fqaaa-aaaaa-aaaaq-cai"' canister_ids.json) > canister_ids.json
) || say fail fail fail



echo Setting the cycles exchange rate...
  ./scripts/propose --to propose-xdr-icp-conversion-rate --dfx-network "$DFX_NETWORK" --jfdi

  # Allow the cmc canister to create canisters anywhere.
  # Note: The proposal is acepted and executed immediately because there are no neurons apart from the test user.
  # Note: Local dfx has no subnets.
  [[ "$DFX_NETWORK" == "local" ]] || {
    echo Setting the list of subnets CMC is authorized to create canisters in...
    ./scripts/propose --to set-authorized-subnetworks --dfx-network "$DFX_NETWORK" --jfdi
  }


( set -euxo pipefail
  ./deploy.sh --ii "$DFX_NETWORK"
  ./deploy.sh --nns-dapp "$DFX_NETWORK"
  say deployed frontends
) || say fail fail fail



( set -euxo pipefail
  ./deploy.sh --sns-wasm --ctl-nobuild-nns "$DFX_NETWORK"
  say deployed sns-wasm
) || say fail fail fail


( set -euxo pipefail
  ./deploy.sh --ii "$DFX_NETWORK"
  ./deploy.sh --nns-dapp "$DFX_NETWORK"
  say redeployed frontends
) || say fail fail fail


./mk-sns-config
./deploy.sh --sns --ctl-nobuild-nns "$DFX_NETWORK"


/home/max/dfn/nns-dapp/branches/testnet-updates/scripts/testnet-set-canister-ids
jq 'to_entries | map({key:.key, value: { (env.DFX_NETWORK): .value[env.DFX_NETWORK] }}) | del(..|nulls) | from_entries' canister_ids.json


( set -euxo pipefail
  echo DEPLOY OPEN_CHAT
  cd "$OC_DIR"
  git checkout "$OC_COMMIT"
  git reset --hard "$OC_COMMIT"
  ( cd "$ND_DIR" && git show origin/testnets:testnets/canister_ids.json ) > canister_ids.json
  dfx identity use openchat

  RANDOM_ID=rwlgt-iiaaa-aaaaa-aaaaa-cai
  scripts/deploy-testnet.sh openchat "$RANDOM_ID"
)
