import { E8S_PER_ICP, TRANSACTION_FEE_E8S } from "./icp.constants";

export const MIN_NEURON_STAKE_SPLITTABLE =
  2 * E8S_PER_ICP + TRANSACTION_FEE_E8S;

export const MAX_NEURONS_MERGED = 2;
export const MIN_MATURITY_MERGE = TRANSACTION_FEE_E8S;
export const MIN_NEURON_STAKE = E8S_PER_ICP;
export const MAX_CONCURRENCY = 10;

export const MIN_VERSION_MERGE_MATURITY = "2.0.6";
