#!/usr/bin/env bash
set -euo pipefail

TOP_DIR=$(git rev-parse --show-toplevel)
cd "$TOP_DIR/frontend"

# Checks for unauthorized relative imports in a file
# We skip two SvelteKit specific cases:
# 1. The $types import: SvelteKit generates virtual types for each page/layout that has to be imported like `./$types`
# 2. The home page route: Special case in our app that requires relative imports due to SvelteKit's routing structure
# 3. Imports in the style section of Svelte components
git grep -n "from ['\"]\.\./" -- "src/**/*.svelte" "src/**/*.ts" \
  | grep -v '/\$types' \
  | grep -v 'src/routes/(nns)/(app)/home/+page.svelte' \
  | grep -v 'src/routes/(app)/(home)/+page.svelte' \
  | grep -v '@use.*\.\.' \
  | grep -v '@import.*\.\.'

exit $?
