#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$(realpath "$0")")/.."

# Get the asset
if test -n "${1:-}"; then
  DOWNLOAD_PATH="$1"
  DOWNLOAD_FILENAME="$(basename "$DOWNLOAD_PATH")"
else
  DOWNLOADS_DIR="$HOME/Downloads"
  echo
  read -rn 1 -p "Please download the 'Backend wasm module.zip' docker build artifact from github to $DOWNLOADS_DIR and press enter...  "

  # Gets the most recent 'Backend wasm module' download:
  # shellcheck disable=SC2010 # we really do want this, not globbing.
  DOWNLOAD_FILENAME="$(ls -t "$DOWNLOADS_DIR" | grep -E '^Backend wasm module( [(][0-9]+[)])?.zip$' | head -n1)"
  DOWNLOAD_PATH="$DOWNLOADS_DIR/$DOWNLOAD_FILENAME"
  echo "Sourcing WASM from: $DOWNLOAD_PATH"
fi

WASM_PATH="$(jq -rc '.canisters["nns-dapp"].wasm' dfx.json)"
WASM_FILENAME="nns-dapp.wasm"
UNZIP_TMPDIR="$(mktemp -d)"
mkdir -p "$(dirname "$WASM_PATH")"
cp "$DOWNLOAD_PATH" "$UNZIP_TMPDIR"
pushd "$UNZIP_TMPDIR"
unzip "$DOWNLOAD_FILENAME"
popd
mv "$UNZIP_TMPDIR/$WASM_FILENAME" "$WASM_PATH"
DEPLOY_ENV=nobuild dfx deploy --no-wallet --network testnet

set +x
echo "Deployed to: https://$(jq -jc '.["nns-dapp"].testnet' canister_ids.json).nnsdapp.dfinity.network"
