#!/usr/bin/env bash
set -euxo pipefail
cd "$(dirname "$(realpath "$0")")/.."

set -x
time xargs -P8 -I{} bash -c "{}" <<EOF
./scripts/fmt-frontend
./scripts/fmt-e2e
./scripts/fmt-json
./scripts/fmt-rs
./scripts/fmt-sh
./scripts/fmt-yaml
./scripts/fmt-changelogs
EOF
