#!/usr/bin/env bash
set -euxo pipefail
cd "$(dirname "$(realpath "$0")")/.."

# shellcheck disable=SC2094 # The file is completely read before it is written so this is correct and safe.
cat <<<"$(jq . dfx.json)" >dfx.json
