#!/usr/bin/env bash
cd "$(dirname "$(realpath "$0")")/.." || exit

list_files() {
  git ls-files | while read -r line; do if [[ "$line" = *.sh ]] || file "$line" | grep -qw Bourne; then echo "$line"; fi; done
}

case "${1:-}" in
--list) list_files ;;
--check) list_files | xargs -I{} shfmt -i 2 -d "{}" ;;
*) list_files | xargs -I{} shfmt -i 2 -l -w "{}" ;;
esac
