#!/usr/bin/env bash
cd "$(dirname "$(realpath "$0")")/.." || exit

list_files() {
  git ls-files | grep -E '[.]ya?ml$'
}

case "${1:-}" in
--list) list_files ;;
--check) list_files | while read -r line; do diff <(yq . "$line") "$line"; done | if grep .; then exit 1; fi ;;
*)
  list_files | while read -r line; do yq --inplace . "$line"; done
  ;;
esac
