#!/usr/bin/env bash
set -euo pipefail
# Craete an empty assets file, if there is none.
test -e assets.tar.xz || touch assets.tar.xz
# Lint the rust code
cargo clippy --locked --target wasm32-unknown-unknown --all-features -- -D warnings -W clippy::pedantic -A clippy::module-name-repetitions -A clippy::struct-field-names -A clippy::missing_errors_doc -A clippy::missing_panics_doc
# TODO: Add the error and panic documentation, then update the lint.
