#!/usr/bin/env bash
set -euo pipefail
# Craete an empty assets file, if there is none.
test -e assets.tar.xz || touch assets.tar.xz
# Lint the rust code
cargo clippy --target wasm32-unknown-unknown --all-features -- -D warnings
