#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$(realpath "$0")")/.." || exit

# Lists all bash files in the repo.
list_files() {
  git ls-files | filter
}

# Selects bash files; filenames are read from stdin, one line per filename, bash filenames are written to stdout.
filter() {
  while read -r line; do if [[ "$line" = *.sh ]] || file "$line" | grep -qw Bourne; then echo "$line"; fi; done
}

lint=(shellcheck -e SC1090 -e SC2119 -e SC1091)

case "${1:-}" in
"") list_files | xargs -P4 -I{} "${lint[@]}" "{}" ;;
--modified) git ls-files --modified | filter | xargs -P8 -I{} "${lint[@]}" "{}" ;;
*) "${lint[@]}" "${@}" ;;
esac
