#!/usr/bin/env bash
set -xeuo pipefail

# Test that no new entries are added to already released CHANGELOG sections.

SOURCE_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

git diff "$(git merge-base HEAD origin/main)" "$SOURCE_DIR/../CHANGELOG-Nns-Dapp.md"

exit 1
