#!/usr/bin/env bash
set -xeuo pipefail

# Test that no new entries are added to already released CHANGELOG sections.

CHANGELOG="CHANGELOG-Nns-Dapp.md"
MAIN_ANCESTOR="$(git merge-base HEAD origin/main)"

ignoreSigPipe() {
  error="$?"
  echo "Ignoring error $error"
  return 0
}

echo test 1
seq 10000 | head -1 || ignoreSigPipe

echo test 2
seq 10000 | (head -1 && cat /dev/null) || ignoreSigPipe

echo test 3

if ! LAST_ADDED_ENTRY_CONTENT="$(git diff "$MAIN_ANCESTOR" "$CHANGELOG" | grep '^+[*-]' | tail -1 | sed -e 's/^+//')"; then
  echo "PASSED: No new entries were added to $CHANGELOG"
  exit 0
fi

LAST_ADDED_ENTRY_LINE_NUMBER="$(grep --fixed-string -n -m 1 -- "$LAST_ADDED_ENTRY_CONTENT" "$CHANGELOG" | cut -d: -f1)"
# Sometimes `git show` exits with SIGPIPE (141). This is probably because the
# `grep` exits early, and `git show` is trying to write to a pipe that's no
# longer there. We ignore this error.
LAST_RELEASE_HEADING="$(git show origin/main:CHANGELOG-Nns-Dapp.md | (grep -m 1 '^## Proposal [0-9]\+$'; cat > /dev/null) )"
LAST_RELEASE_LINE_NUMBER="$(grep -n -m 1 "$LAST_RELEASE_HEADING" "$CHANGELOG" | cut -d: -f1)"

if (("$LAST_ADDED_ENTRY_LINE_NUMBER" > "$LAST_RELEASE_LINE_NUMBER")); then
  echo "ERROR: $CHANGELOG entries should not be added to existing releases." >&2
  exit 1
fi

echo "PASSED"
