#!/usr/bin/env bash
set -euo pipefail

# Test that no new entries are added to already released CHANGELOG sections.

SOURCE_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

git diff HEAD~1 "$SOURCE_DIR/../CHANGELOG-Nns-Dapp.md"

exit 1
