#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$(realpath "$0")")/.."

print_help() {
  cat <<-EOF
	Propose to upgrade a testnet NNS-dapp canister to the current build.

	Usage:
	- Put a copy of ic-admin to match the testnet in the root of the repository
	- Run: ./$(basename "$0") testnet
	EOF
}

on_exit() {
  set +x
  exit_code=$?
  ((exit_code == 0)) || {
    printf "\n\nERROR: exiting with code %s\n\n" $exit_code
    print_help | sed 's/^/USAGE: /g'
    exit $exit_code
  } >&2
}
trap on_exit EXIT

NETWORK=testnet
while (($# > 0)); do
  arg="$1"
  shift 1
  case "$arg" in
  --help)
    print_help
    exit 0
    ;;
  *) NETWORK="$arg" ;;
  esac
done

NETWORK="${1:-testnet}"
WASM_FILE=nns-dapp.wasm
test -e "$WASM_FILE" || ./scripts/docker-build
SHA="$(sha256sum "$WASM_FILE" | awk '{print $1}')"
PROVIDER="$(NETWORK="$NETWORK" jq -er .networks[env.NETWORK].providers[0] dfx.json)"
CANISTER_ID="$(dfx canister --network "$NETWORK" id nns-dapp)"
test -e ./ic-admin || {
  printf "  %s\n" \
    "" \
    "Place a copy of ic-admin in the repo root as in the testnet installation instructions:" \
    "https://www.notion.so/SOP-Deploy-NNS-dapp-to-mainnet-5347d7438dc04b088c61abd0edb3abd4" \
    ""
  read -rp "Press enter to continue..." _
}

set -x
./ic-admin --nns-url "$PROVIDER" propose-to-change-nns-canister --test-neuron-proposer --canister-id "$CANISTER_ID" --mode upgrade --wasm-module-path "$WASM_FILE" --wasm-module-sha256 "$SHA" --summary-file ./README.md
