#!/usr/bin/env bash
set -euxo pipefail
THIS_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
gh workflow run testnet --ref "$THIS_BRANCH"
sleep 5
gh run watch "$(gh run list --workflow=testnet.yml --limit 1 --json databaseId | jq -r '.[0].databaseId')"

