#!/usr/bin/env bash
set -euo pipefail
SOURCE_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
PATH="$SOURCE_DIR:$PATH"

# shellcheck disable=SC2317 # The help function is called by the argument parser.
print_help() {
  cat <<-"EOF"
	Runs Rust integration tests.
	EOF
}

# Source the clap.bash file ---------------------------------------------------
source "$SOURCE_DIR/clap.bash"
# Define options
# Source the output file ----------------------------------------------------------
source "$(clap.build)"

REPO_ROOT="$SOURCE_DIR/.."
cd "$REPO_ROOT"

test -d out || {
  echo "ERROR: Build artefacts are needed in ./out for integration tests."
  echo "       Please run: ./scripts/docker-build --network local"
  exit 1
} >&2

test -x pocket-ic || {
  echo "ERROR: The pocket-ic executable is needed in the repository root."
  echo "       Please download an executable for your platform, to ./pocket-ic and make it executable."
  exit 1
}

PROPTEST_CASES=20 POCKET_IC_BIN=$PWD/pocket-ic time cargo test --test '*' -- --nocapture
