#!/usr/bin/env bash
set -euo pipefail

: "Getting URL from latest redirect..."
II_URL="$(
  set +o pipefail # We truncate the curl output, this is fine.
  curl -v https://github.com/dfinity/internet-identity/releases/latest/download/internet_identity_dev.wasm 2>&1 |
    awk '(($1 == "<") && ($2 == "location:")){print $3; exit 0}' |
    tr -d '[:space:]'
)"
echo "II_URL: ${II_URL}"

: "Sanity checking URL..."
unexpected_chars="$(printf "%s" "$II_URL" | tr -d 'a-zA-Z0-9/:._' | tr -d -- -)"
test -z "${unexpected_chars:-}" || {
  printf "Refusing to use URL containing chars: '%q'\n" "${unexpected_chars}"
  exit 1
}
[[ "$II_URL" = https://github.com/dfinity/internet-identity/releases/* ]] || {
  echo "Refusing to use URL from unexpected source."
  exit 1
}

: "Defining build script..."
II_BUILD="$(printf 'curl --fail -sSL "%s" -o internet_identity.wasm' "$II_URL")"
echo "II_BUILD: ${II_BUILD}"
echo Verifying that the build script works...
printf "%s" "$II_BUILD" | bash -r

export II_BUILD
tmp="$(mktemp dfx.json.XXXXXXXX)"
jq '.canisters.internet_identity.build=env.II_BUILD' dfx.json >"$tmp"

: "Checking whether there is any meaningful change..."
if diff <(jq . dfx.json) <(jq . "$tmp"); then
  echo "No change"
  rm "$tmp"
else
  mv "$tmp" dfx.json
fi
echo FIN
