#!/usr/bin/env bash
set -euo pipefail
SOURCE_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
print_help() {
  cat <<-"EOF"

	Fetches the candid for NNS canisters.
	EOF
}
# Source the clap.bash file ---------------------------------------------------
source "$SOURCE_DIR/clap.bash"
# Define options
clap.define short=c long=ic_commit desc="The IC commit to use" variable=DFX_IC_COMMIT default=""
clap.define long=crate desc="'proposals' or 'sns_aggregator' or 'all'" variable=CRATE default="all"
# Source the output file ----------------------------------------------------------
source "$(clap.build)"

if [[ "${CRATE:-}" = "all" ]]; then
  for crate in proposals sns_aggregator; do
    "$0" --ic_commit "$DFX_IC_COMMIT" --crate "$crate"
  done
  exit 0
fi

: "Make sure that DFX_IC_COMMIT is defined"
[[ "${DFX_IC_COMMIT:-}" != "" ]] || {
  echo "ERROR: Please specify which ic commit to use."
  echo "  --ic_commit SOME_COMMIT"
  exit 1
} >&2

: "Bump IC_COMMIT in dfx.json"
bump_ic_commit() {
  export IC_COMMIT_CONFIG_FIELD="$1"
  NEW_CONFIG="$(DFX_IC_COMMIT="$DFX_IC_COMMIT" jq '.defaults.build.config[env.IC_COMMIT_CONFIG_FIELD] = (env.DFX_IC_COMMIT)' "$SOURCE_DIR/../dfx.json")"
  [[ "$NEW_CONFIG" != "" ]] || {
    echo "ERROR: Failed to set ${IC_COMMIT_CONFIG_FIELD}  in dfx.json.  Please verify that dfx.json is valid JSON."
    exit 1
  } >&2
  printf "%s\n" "$NEW_CONFIG" >"$SOURCE_DIR/../dfx.json"
}

: "Get the latest did files"
{
  : "Get the did files"
  IC_URL="https://raw.githubusercontent.com/dfinity/ic/${DFX_IC_COMMIT}"
  did_curl() {
    local crate="$1"
    local canister="$2"
    local upstream_path="$3"
    local local_path="declarations/used_by_${crate}/${canister}/${canister}.did"
    mkdir -p "$(dirname "$local_path")"
    {
      echo "//! Candid for canister \`$canister\` obtained by \`scripts/update_ic_commit\` from: <$IC_URL$upstream_path>"
      curl -SsfL --retry 5 "$IC_URL$upstream_path"
    } >"${local_path}"
  }
  if [[ "$CRATE" = "proposals" ]]; then
    bump_ic_commit IC_COMMIT_FOR_PROPOSALS
    did_curl proposals nns_governance /rs/nns/governance/canister/governance.did
    did_curl proposals nns_registry /rs/registry/canister/canister/registry.did
    did_curl proposals sns_wasm /rs/nns/sns-wasm/canister/sns-wasm.did
  elif [[ "$CRATE" = "sns_aggregator" ]]; then
    bump_ic_commit IC_COMMIT_FOR_SNS_AGGREGATOR
    did_curl sns_aggregator sns_governance /rs/sns/governance/canister/governance.did
    did_curl sns_aggregator sns_root /rs/sns/root/canister/root.did
    did_curl sns_aggregator sns_swap /rs/sns/swap/canister/swap.did
    did_curl sns_aggregator sns_wasm /rs/nns/sns-wasm/canister/sns-wasm.did
    did_curl sns_aggregator sns_ledger /rs/ledger_suite/icrc1/ledger/ledger.did
  else
    echo "ERROR: --crate should be 'proposals' or 'sns_aggregator' or 'all'."
    exit 1
  fi
}

: "All done"
echo FIN
