#!/usr/bin/env bash
set -euo pipefail
SOURCE_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

print_help() {
  cat <<-"EOF"

	Updates IC repo deps in Cargo.toml files to the latest release.
	EOF
}
# Source the clap.bash file ---------------------------------------------------
source "$SOURCE_DIR/clap.bash"
# Define options
clap.define short=r long=ref desc="The IC commit/tag/release to use" variable=IC_REF default="latest"
# Source the output file ----------------------------------------------------------
source "$(clap.build)"

if [[ "${IC_REF:-}" = "latest" ]]; then
  IC_REF="$(curl -sSL https://api.github.com/repos/dfinity/ic/releases/latest | jq .tag_name -r)"
  echo "Latest release is $IC_REF."
fi

TOP_DIR=$(git rev-parse --show-toplevel)

for cargo_toml_file in "Cargo.toml" $(find "$TOP_DIR/rs" -name "Cargo.toml"); do
  for dep in $(grep -o "{ git = \"https://github.com/dfinity/ic\", rev = \"[^\"]*\"" "$cargo_toml_file" | sed -E 's@.* rev = "(.*)"@\1@' | uniq); do
    echo "Updating $cargo_toml_file, changing '$dep' to '$IC_REF'."
    sed -i.bak -e "s@${dep}@${IC_REF}@" "$cargo_toml_file"
    rm "$cargo_toml_file.bak"
  done
done

cargo update
