#!/usr/bin/env bash
set -euo pipefail
SOURCE_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
print_help() {
  cat <<-EOF
	Gets the instructions used by the last post_upgrade function call.

	Note: The instruction consumption is independent of network, it depends
	      on the replica which is usually the same.  The cycle cost is a factor
	      if the instruction count and the factor depends on the number of nodes
	      in a subnet, and that does differ significantly between subnets.
	EOF
}
# Source the clap.bash file ---------------------------------------------------
source "$SOURCE_DIR/../clap.bash"
# Define options
clap.define short=n long=network desc="The dfx network to use" variable=DFX_NETWORK default="local"
# Source the output file ----------------------------------------------------------
source "$(clap.build)"

dfx canister call --network "$DFX_NETWORK" nns-dapp get_stats | idl2json | node -e 'counters=JSON.parse(require("fs").readFileSync(0).toString()).performance_counts.reduce((d,e)=>(d[e.name]=Number(e.instruction_count),d), {});console.log(counters["post_upgrade stop"] - counters["post_upgrade start"])'
