name: 'Set up Playwright e2e'
description: |
  Set up a test environment for Playwright end-to-end tests.
runs:
  using: "composite"
  steps:
    - name: Checkout nns-dapp
      uses: actions/checkout@v3
    - name: Get nns-dapp
      uses: actions/download-artifact@v3
      with:
        name: nns-dapp
    - name: Get sns_aggregator_dev
      uses: actions/download-artifact@v3
      with:
        name: sns_aggregator_dev
    - name: Start snapshot environment
      uses: ./.github/actions/start_dfx_snapshot
      with:
        nns_dapp_wasm: 'nns-dapp.wasm.gz'
        sns_aggregator_wasm: 'sns_aggregator_dev.wasm.gz'
        # Upgrade innstead of reinstall to keep the preloaded SNSes.
        sns_aggregator_install_mode: 'upgrade'
    - name: Generate .env configuration for Playwright end-to-end tests
      shell: bash
      run: |
        DFX_NETWORK=local ./config.sh
    - name: Prepare for Playwright end-to-end tests
      shell: bash
      working-directory: frontend
      run: |
        npm ci
        npx playwright install --with-deps firefox
