name: Flutter tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEPLOY_ENV: mainnet

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile js-agent
        run: npm run build
        working-directory: ./js-agent

      - name: Flutter setup
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.6'
          channel: 'stable'

      - run: flutter pub get
        working-directory: ./dfinity_wallet

      - run: flutter build web --web-renderer canvaskit --release --no-sound-null-safety
        working-directory: ./dfinity_wallet

      - run: flutter test
        working-directory: ./dfinity_wallet
