name: Reproducible Docker Builds
# Simulates end users verifying builds published by Dfinity:
# - Runs a docker build with an empty docker cache.
#   Note: This makes builds slow but is more representative of the end user experience.
# - NOT DONE: Verify that these builds match our release artifacts.  This would correspond to third
#   party verifiers getting consistent hashes that differ from our release.
on:
  push:
    branches:
      # This is the recommended development branch for this workflow; pushing it will trigger a build.
      - reproducible
    tags:
      # The tag used when preparing a release.
      - release-candidate
  schedule:
    # Nightly test.
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
jobs:
  docker_build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # Helps with debugging
      - name: Show versions
        run: |
          echo bash --version
          bash --version
          echo docker --version
          docker --version
      - name: Build
        run: ./scripts/docker-build
      - name: 'Upload nns-dapp wasm module'
        uses: actions/upload-artifact@v7
        with:
          name: nns-dapp-mainnet-wasm
          path: nns-dapp.wasm.gz
          retention-days: 3
      - name: 'Upload assets'
        uses: actions/upload-artifact@v7
        with:
          name: nns-dapp-assets
          path: assets.tar.xz
          retention-days: 3
      - name: 'Output the wasm hash'
        run: |
          mkdir -p hashes
          sha256sum nns-dapp.wasm.gz > "hashes/nns-dapp-wasm_sha256.txt"
      - name: 'Output the assets hash'
        run: |
          sha256sum assets.tar.xz > "hashes/assets_sha256.txt"
      - name: 'Upload hashes'
        uses: actions/upload-artifact@v7
        with:
          name: hashes
          path: hashes/*.txt
  compare_hashes:
    runs-on: ubuntu-latest
    needs: [docker_build]
    steps:
      - name: Get hashes
        uses: actions/download-artifact@v8
        with:
          name: hashes
          path: hashes
      - name: Print hashes
        run: |
          echo Hashes:
          grep -r . hashes/ | awk -F: '{printf "%s: %s\n", $2, $1}' | sort
          # If the assets hashes differ, the Wasm hashes will also
          # differ, so we only check the Wasm hashes.
          (( $(cat hashes/nns-dapp-wasm_*.txt | sort | uniq | wc -l) == 1 ))
  check_passes:
    needs: ["docker_build", "compare_hashes"]
    if: ${{ always() }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/needs_success
        with:
          needs: '${{ toJson(needs) }}'
      - name: Notify Slack on failure
        uses: dfinity/internet-identity/.github/actions/slack@release-2023-08-28
        if: ${{ failure() }}
        with:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MESSAGE: "Reproducible docker build test failed for ${{ github.ref_name }}"
