name: Security audit
on:
  schedule:
    # Run daily:
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Default: Enables a button in the github UI to trigger the workflow manually.
jobs:
  rust-audit:
    name: Rust Package Audit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cargo Package Audit
        run: cargo audit
  js-audit:
    name: Javascript Package Audit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Audit packages
        # TODO: Create npm workspaces so that we can run cargo audit just once, at the top level.
        run: |
          set -eu
          git ls-files | grep -E 'package-lock.json$' |\
          while read line ; do
            pushd "$(dirname "$line")"
            printf "\n\n\n\nAuditing %s\n" "$line"
            npm audit
            popd
          done
