name: Security audit
on:
  schedule:
    # Run daily:
    - cron: '0 0 * * *'
  pull_request:
    # Default: Run on every PR.
  workflow_dispatch:
    # Default: Enables a button in the github UI to trigger the workflow manually.
jobs:
  rust-audit:
    name: Rust Package Audit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cargo Package Audit
        run: cargo audit
  js-audit:
    name: Javascript Package Audit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Audit packages
        run: npm audit
