name: Selenium tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device: [ 'desktop' ]
      # Make sure that one failing test does not cancel all other matrix jobs
      fail-fast: false
    env:
      DFX_VERSION: 0.8.3

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install DFX
        run: |
          echo Install DFX Version: "$DFX_VERSION"
          yes | sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"

      # Helps with debugging
      - name: Show versions
        run: |
          echo dfx --version
          dfx --version
          echo node --version
          node --version
          echo npm --version
          npm --version

      - name: Run proxy
        working-directory: proxy
        run: |
          npm ci
          npm run start &

        # TODO: remove screenshots and commit screenshots

      - name: build the canister
        run: ./scripts/docker-build # TODO: fetch from build

      - name: start the replica
        run: dfx start --background

      - name: Deploy NNS Dapp
        run: |
          DEPLOY_ENV=nobuild dfx deploy --no-wallet --network local

        # TODO: move this back to after the deploy
      - name: prepare and run the test suite
        working-directory: e2e-tests
        run: |
          npm install
          npm run install-webdrivers
          npm run test

      - run: dfx stop

      - name: Archive test logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: selenium-test-log-${{ matrix.device }}
          path: wdio.log
