name: Update Snapshots
on:
  workflow_dispatch:
jobs:
  update_snapshots:
    runs-on: ubuntu-20.04
    steps:
      - name: Fail if branch is main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "This workflow should not be triggered with workflow_dispatch on main"
          exit 1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Run Playwright tests
        run: npm run test-e2e:snapshots
        working-directory: ./frontend
      - name: Commit Playwright updated snapshots
        uses: EndBug/add-and-commit@v9
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          add: ./frontend/snapshots
          default_author: github_actions
          message: "\U0001F916 update snapshots"
